### ISSUE TITLE
[Bug] libpulsarwithdeps.a misses some symbols on Linux or macOS

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar-client-cpp#512]
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/pulsar-client-cpp/issues) and found nothing similar.

### Version

https://dist.apache.org/repos/dist/dev/pulsar/pulsar-client-cpp/pulsar-client-cpp-3.8.0-candidate-2/

### Minimal reproduce step

Download the macos-arm64.zip and follow the guide [here](https://github.com/apache/pulsar-client-cpp/wiki/Verify-the-candidate-release#macos-users) to verify it.

### What did you expect to see?

The application run successfully

### What did you see instead?

```
% clang++ main.cc ./lib/libpulsarwithdeps.a -std=c++11 -I./include
Undefined symbols for architecture arm64:
  "_bitset_resize", referenced from:
      _roaring_bitmap_to_bitset in libpulsarwithdeps.a[1287](roaring.c.o)
      _roaring_bitmap_to_bitset in libpulsarwithdeps.a[1287](roaring.c.o)
ld: symbol(s) not found for architecture arm64
```

### Anything else?

This should be caused by the static library of [roaring](https://github.com/apache/pulsar-client-cpp/blob/386dedc47bde8c46fae1705afdf66e4b972c7447/vcpkg.json#L47) is not included in the `*.a` file.

This dependency was introduced since https://github.com/apache/pulsar-client-cpp/pull/497, so it's a regression

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by BewareMyPower** [comment]
The workaround is not to use `ar -x` to extract `*.a` files to `*.o` files. For example, on macOS, the following trick works:

```diff
diff --git a/build-support/merge_archives.sh b/build-support/merge_archives.sh
index 065130d..d7e3c53 100755
--- a/build-support/merge_archives.sh
+++ b/build-support/merge_archives.sh
@@ -20,6 +20,7 @@

 set -e

+ROOT="$pwd/.."
 MERGED_LIBRARY=$1
 shift
 ITEMS=$*
@@ -44,7 +45,9 @@ for ITEM in $ITEMS; do
     LIBS="$LIBS $LIB_NAME/*.o"
     cd ..
 done
+LIBS="$LIBS $ROOT/vcpkg/buildtrees/roaring/arm64-osx-dbg/src/CMakeFiles/roaring.dir/bitset.c.o"

+set -x
 ar -qc $MERGED_LIBRARY $LIBS
```

P.S. Change `dbg` to `rel` in release.

However, it's a bit complicated that we need to write a new script to scan object files (`*.o)` from dependencies directly under the `vcpkg/buildtrees` directory.  In addition, the build on Windows is different that I don't have time to verify if the Windows library has the same issue.

A quick fix is to remove the libroaring dependency and use an alternative for `Roaring64Map` from libroaring for now. /cc @shibd
